// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    IClose: typeof import('./icon/i-close.vue')['default']
    IFixed: typeof import('./icon/i-fixed.vue')['default']
    IMin: typeof import('./icon/i-min.vue')['default']
    IMoon: typeof import('./icon/i-moon.vue')['default']
    ISun: typeof import('./icon/i-sun.vue')['default']
  }
}

export { }
